export default {
  name: 'siteSettings',
  title: 'Site Settings',
  type: 'document',
  groups: [
    { name: 'hero', title: 'Hero Section' },
    { name: 'about', title: 'About Section' },
    { name: 'contact', title: 'Contact Info' },
    { name: 'branding', title: 'Branding' },
    { name: 'social', title: 'Social Media' },
    { name: 'legal', title: 'Legal / License' },
    { name: 'pages', title: 'Page Content' },
  ],
  fields: [
    { name: 'siteTitle', title: 'Site Title', type: 'string' },

    // Hero
    { name: 'heroHeadline', title: 'Hero Headline', type: 'string', group: 'hero' },
    { name: 'heroSubheadline', title: 'Hero Subheadline', type: 'text', rows: 2, group: 'hero' },
    {
      name: 'heroMediaType', title: 'Hero Media Type', type: 'string', group: 'hero',
      options: { list: [{ title: 'Image Slider', value: 'images' }, { title: 'Video Background', value: 'video' }], layout: 'radio' },
      initialValue: 'images',
    },
    {
      name: 'heroImages', title: 'Hero Images', type: 'array', group: 'hero',
      of: [{ type: 'image', options: { hotspot: true }, fields: [{ name: 'alt', title: 'Alt Text', type: 'string' }] }],
    },
    { name: 'heroVideo', title: 'Hero Video', type: 'file', group: 'hero', options: { accept: 'video/*' } },

    // About
    { name: 'contractorName', title: 'Contractor / Company Name', type: 'string', group: 'about' },
    { name: 'contractorTitle', title: 'Title / Specialty', type: 'string', group: 'about' },
    { name: 'contractorPhoto', title: 'Photo', type: 'image', group: 'about', options: { hotspot: true } },
    { name: 'aboutHeadline', title: 'About Headline', type: 'string', group: 'about' },
    { name: 'aboutText', title: 'About Text', type: 'text', rows: 10, group: 'about' },
    {
      name: 'aboutStats', title: 'Stats', type: 'array', group: 'about',
      of: [{ type: 'object', fields: [
        { name: 'value', title: 'Value', type: 'string' },
        { name: 'label', title: 'Label', type: 'string' },
      ], preview: { select: { title: 'value', subtitle: 'label' } } }],
    },
    {
      name: 'aboutSubtitle',
      title: 'About Page Subtitle',
      type: 'text',
      rows: 3,
      group: 'about',
      description: 'Displayed below the main headline on the About page',
    },
    {
      name: 'teamMembers',
      title: 'Team Members',
      type: 'array',
      group: 'about',
      description: 'Team/founders displayed on the About page',
      of: [{
        type: 'object',
        name: 'teamMember',
        title: 'Team Member',
        fields: [
          { name: 'name', title: 'Full Name', type: 'string', validation: (Rule: any) => Rule.required() },
          { name: 'title', title: 'Title / Role', type: 'string', description: 'e.g., Co-Founder & CEO' },
          { name: 'subtitle', title: 'Subtitle / Credential', type: 'string', description: 'e.g., Mechanical Engineer' },
          { name: 'focus', title: 'Focus / Description', type: 'text', rows: 3, description: 'What this person focuses on' },
          { name: 'photo', title: 'Photo', type: 'image', options: { hotspot: true } },
          { name: 'linkedinUrl', title: 'LinkedIn URL', type: 'url' },
          { name: 'email', title: 'Email Address', type: 'string', description: 'Optional — displays a mail icon for quick contact' },
        ],
        preview: {
          select: {
            title: 'name',
            subtitle: 'title',
            media: 'photo',
          },
        },
      }],
    },
    {
      name: 'teamClosingHeadline',
      title: 'Team Section Closing Headline',
      type: 'string',
      group: 'about',
      description: 'Headline displayed after the team members grid, e.g., a team motto or standard',
    },
    {
      name: 'teamClosingText',
      title: 'Team Section Closing Text',
      type: 'text',
      rows: 4,
      group: 'about',
      description: 'Body text displayed below the closing headline',
    },

    // Contact
    { name: 'phone', title: 'Phone', type: 'string', group: 'contact' },
    { name: 'email', title: 'Email', type: 'string', group: 'contact' },
    { name: 'address', title: 'Address', type: 'text', rows: 2, group: 'contact' },
    { name: 'serviceArea', title: 'Service Area', type: 'string', group: 'contact', description: 'e.g., "Greater Austin Area"' },
    { name: 'officeHours', title: 'Office Hours', type: 'text', rows: 3, group: 'contact' },

    // Branding
    { name: 'logo', title: 'Logo', type: 'image', group: 'branding' },
    { name: 'favicon', title: 'Favicon', type: 'image', group: 'branding' },

    // Social
    { name: 'instagram', title: 'Instagram URL', type: 'url', group: 'social' },
    { name: 'facebook', title: 'Facebook URL', type: 'url', group: 'social' },
    { name: 'linkedin', title: 'LinkedIn URL', type: 'url', group: 'social' },
    { name: 'youtube', title: 'YouTube URL', type: 'url', group: 'social' },
    { name: 'yelp', title: 'Yelp URL', type: 'url', group: 'social' },
    { name: 'google', title: 'Google Business URL', type: 'url', group: 'social' },
    { name: 'houzz', title: 'Houzz URL', type: 'url', group: 'social' },
    { name: 'nextdoor', title: 'Nextdoor URL', type: 'url', group: 'social' },

    // Legal
    { name: 'licenseNumber', title: 'Contractor License Number', type: 'string', group: 'legal' },
    { name: 'licenseState', title: 'License State', type: 'string', group: 'legal' },
    { name: 'insuranceInfo', title: 'Insurance Info', type: 'string', group: 'legal' },
    { name: 'bondInfo', title: 'Bond Info', type: 'string', group: 'legal' },
    {
      name: 'termsOfService',
      title: 'Terms of Service',
      type: 'text',
      rows: 20,
      group: 'legal',
      description: 'Full Terms of Service text. Displayed on /terms page.',
    },
    {
      name: 'privacyPolicy',
      title: 'Privacy Policy',
      type: 'text',
      rows: 20,
      group: 'legal',
      description: 'Full Privacy Policy text. Displayed on /privacy page.',
    },

    // Page Content
    {
      name: 'projectsPageHeadline',
      title: 'Projects Page — Headline',
      type: 'string',
      group: 'pages',
      description: 'Main heading on the Projects page',
    },
    {
      name: 'projectsPageDescription',
      title: 'Projects Page — Description',
      type: 'text',
      rows: 3,
      group: 'pages',
      description: 'Subtitle text below the heading on the Projects page',
    },
    {
      name: 'servicesPageHeadline',
      title: 'Services Page — Headline',
      type: 'string',
      group: 'pages',
      description: 'Main heading on the Services page',
    },
    {
      name: 'servicesPageDescription',
      title: 'Services Page — Description',
      type: 'text',
      rows: 3,
      group: 'pages',
      description: 'Subtitle text below the heading on the Services page',
    },
    {
      name: 'testimonialsPageHeadline',
      title: 'Testimonials Page — Headline',
      type: 'string',
      group: 'pages',
      description: 'Main heading on the Testimonials page',
    },
    {
      name: 'testimonialsPageDescription',
      title: 'Testimonials Page — Description',
      type: 'text',
      rows: 3,
      group: 'pages',
      description: 'Subtitle text below the heading on the Testimonials page',
    },
    {
      name: 'faqPageHeadline',
      title: 'FAQ Page — Headline',
      type: 'string',
      group: 'pages',
      description: 'Main heading on the FAQ page',
    },
    {
      name: 'faqPageDescription',
      title: 'FAQ Page — Description',
      type: 'text',
      rows: 3,
      group: 'pages',
      description: 'Subtitle text below the heading on the FAQ page',
    },
    {
      name: 'contactPageHeadline',
      title: 'Contact Page — Headline',
      type: 'string',
      group: 'pages',
      description: 'Main heading on the Contact page',
    },
    {
      name: 'contactPageDescription',
      title: 'Contact Page — Description',
      type: 'text',
      rows: 3,
      group: 'pages',
      description: 'Subtitle text below the heading on the Contact page',
    },
    {
      name: 'heroCtaPrimaryText',
      title: 'Hero Primary Button Text',
      type: 'string',
      group: 'pages',
      description: 'Primary CTA button on hero section (e.g., "View Our Projects")',
      validation: (Rule: any) => Rule.max(30),
    },
    {
      name: 'heroCtaSecondaryText',
      title: 'Hero Secondary Button Text',
      type: 'string',
      group: 'pages',
      description: 'Secondary CTA button on hero section (e.g., "Get a Free Quote")',
      validation: (Rule: any) => Rule.max(30),
    },
    {
      name: 'ctaSectionHeadline',
      title: 'CTA Section Headline',
      type: 'string',
      group: 'pages',
      description: 'Headline for the CTA banner at the bottom of pages',
      validation: (Rule: any) => Rule.max(80),
    },
    {
      name: 'ctaSectionDescription',
      title: 'CTA Section Description',
      type: 'text',
      rows: 2,
      group: 'pages',
      description: 'Description text for the CTA banner',
      validation: (Rule: any) => Rule.max(150),
    },
    {
      name: 'ctaSectionButtonText',
      title: 'CTA Section Button Text',
      type: 'string',
      group: 'pages',
      description: 'Button text for the CTA banner (e.g., "Contact Us")',
      validation: (Rule: any) => Rule.max(30),
    },
    {
      name: 'headerCtaText',
      title: 'Header CTA Button Text',
      type: 'string',
      group: 'pages',
      description: 'CTA button in the header/navigation (e.g., "Get a Free Quote")',
      validation: (Rule: any) => Rule.max(30),
    },
  ],
  preview: { prepare() { return { title: 'Site Settings', subtitle: 'Hero, About, Contact & Branding' } } },
}
